### PR TITLE
Update to 0.5 

### PR DESCRIPTION
**Pull request by sl1pm4t**
This PR updates the plugin to suit drone 0.5. 

I'm not closely familiar with the drone and drone-plugins code base, but have attempted to copy the patterns seen in s3 plugin when it was updated to 0.5. (e.g. the bulk of the plugin logic has been moved to a plugin.go file, dependencies have been vendored etc)

This is currently built and pushed to docker hub as the image `mmorrison/gcs`

### CODE REVIEW

**Comment by sl1pm4t** [comment]
Ping @tboerger, @bradrydzewski 
Any chance you could review this PR?

**Comment by frapposelli** [comment]
+1 I'm waiting on this as well

**Comment by sl1pm4t** [comment]
Ping @tboerger / @bradrydzewski

**Comment by bradrydzewski** [comment]
For 0.5 we can actually alter the approach to simply wrap the docker plugin. Check out the ecr plugin for 0.5 https://github.com/drone-plugins/drone-ecr/pull/29/files

**Comment by tboerger** [comment]
Sorry for the delay, I will try to review it really soon.

**Comment by tboerger** [comment]
> For 0.5 we can actually alter the approach to simply wrap the docker plugin. Check out the ecr plugin for 0.5 https://github.com/drone-plugins/drone-ecr/pull/29/files

This is GCS and not GCR :)

**Comment by sl1pm4t** [comment]
Thanks @tboerger  - I was little confused what that comment meant.

**Comment by sl1pm4t** [comment]
@tboerger / @bradrydzewski - any problems merging this?

**Comment by bradrydzewski** [comment]
is it possible to submit this PR without the `vendor` changes? usually I don't accept vendor updates like this because it is not possible for me to audit such a large changeset.

**Comment by tboerger** [comment]
You should replace codegangsta cli, it have been renamed.

**Comment by tonglil** [comment]
I will attempt to add features in this plugin to the community one by wyattjoh, and if unsuccessful, migrate this to 0.5+ as well.

That one is currently missing several features from this one:
- (granular) acl
- cache_control
- metadata

**Pull request closed without merging**
